# 03. 텐서의 조작

In [ ]:
import torch

## 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(x[1,1]) # 5
print(x[2,0]) # 7
print(x[0,:]) # 0행 전체
print(x[:,2]) # 2열 전체
print(x[[0,1,2],[0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

In [ ]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

## 3-2. 텐서의 크기, 모양 변경
- `torch.view()`

In [ ]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = y.view(5, -1) # -1 -> 자동 계산
print(z)

## 3-3. 텐서의 숫자값 얻기
- `tensor.item()` : 스칼라 값 하나만 존재해야 사용 가능

In [ ]:
x = torch.rand(2)
print(x)
print(x[0])
# print(x.item())
print(x[0].item())

## 3-4. 차원 축소 및 증가

### 차원 축소(제거)
- `torch.squeeze()` : 크기가 1인 차원을 제거함

In [ ]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

### 차원 증가(생성)
- `torch.unsqueeze()` : dim 설정에 따라 차원을 증가시킴
  - dim은 하나의 차원이 추가되는 인덱스

In [ ]:
t = torch.rand(3,3,3)
# print(t)
print(t.shape)

# 0 가장 상위 차원 -> 3 가장 하위차원
ts1 = torch.unsqueeze(t, dim=0)
# print(ts1)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
# print(ts2)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
# print(ts2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
# print(ts2)
print(ts4.shape)

## 3-5. 텐서간 결합

- `torch.stack()` : 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨

In [ ]:
x = torch.tensor([1,4])
y = torch.tensor([2,5])
z = torch.tensor([3,6])
result = torch.stack([x,y,z])
print(result)

a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
result2 = torch.stack([a,b])
print(result2)


- `torch.cat()` : 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성X

In [53]:
a = torch.tensor([[1,2],
                  [3,4]])
b = torch.tensor([[7,8],
                  [9,10]])
result = torch.cat((a,b), dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


## 3-6. 텐서 나누기

- `torch.chunk()` : 텐서를 지정한 개수에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [ ]:
t = torch.rand(3,7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

- `torch.split()` : 지정한 사이즈에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [ ]:
t = torch.rand(3,7)
print(t)

t1, t2, t3 = torch.split(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

In [52]:
t = torch.rand(3,7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2,3,2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.2972, 0.8037, 0.8505, 0.2290, 0.2217, 0.5793, 0.6072],
        [0.0469, 0.0096, 0.0377, 0.2209, 0.5543, 0.6588, 0.5707],
        [0.6697, 0.2717, 0.4262, 0.0971, 0.9974, 0.4765, 0.4629]])
tensor([[0.2972, 0.8037],
        [0.0469, 0.0096],
        [0.6697, 0.2717]])
tensor([[0.8505, 0.2290, 0.2217],
        [0.0377, 0.2209, 0.5543],
        [0.4262, 0.0971, 0.9974]])
tensor([[0.5793, 0.6072],
        [0.6588, 0.5707],
        [0.4765, 0.4629]])
