# 04. Autograd(자동미분)
- Pytorch는 Tensor의 모든 연산에 대해 자동미분이 가능함!
- 자동미분은 역전파에 활용됨
- `requires_grad` : Tensor의 속성으로, True로 설정해야 자동미분이 가능
- `tensor.backward()` : 미분 실행
- `tensor.grad` : 미분값을 확인할 수 있는 속성

In [3]:
import torch

In [28]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
print(y)
# print("미분전:", x.grad)

# y.backward() # 미분실행
# print("미분후:", x.grad)

# z = 3 * y
# print(z)

# z.backward() # 미분실행
# print("z미분후:", x.grad)

tensor([1.], grad_fn=<PowBackward0>)


In [23]:
x = torch.tensor([1.], requires_grad=True)
a = x ** 2
b = a + 1
c = b ** 2
c.backward()
print(x.grad)
result = x.grad.detach()
print(result.requires_grad)
print(result.item())

tensor([8.])
False
8.0


In [26]:
# 다변수 함수 미분
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
z = 2*(x**2) + y**2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([11.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([6.])


In [ ]:
# with torch.no_grad():
# gran_fn을 계산하고 싶지 않을때 사용
# => 모델 훈련 후 test data를 가지고 평가할 때 사용

x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():
  y = x**2
  print(x.requires_grad)
  print(y)
  
print(x.requires_grad)
# y = x**2
y.backward() # with 구문 안쪽의 y로 미분 시도시 에러

True
tensor([1.])
True
