## PyTorch Quiz 2 : 연산

In [1]:
import torch

### 1. 덧셈과 뺄셈 연습
1. [2, 4, 6]으로 초기화된 1D Tensor를 생성하세요.
2. 각 요소에 5를 더한 Tensor를 출력하세요.
3. 각 요소에서 3을 뺀 Tensor를 출력하세요.


In [5]:
# 여기에 코드를 작성합니다
t1 = torch.tensor([2,4,6])
# a = t1 + 5
# b = a -3
# print(a)
# print(b)
t1.add_(5)
print(t1)
t1.sub_(3)
print(t1)

tensor([ 7,  9, 11])
tensor([4, 6, 8])


### 2. Tensor 간의 연산
1. 3x3 크기의 Tensor 2개를 생성하세요.
2. 두 Tensor를 각각 더하고(+), 빼고(-), 곱하고(*), 나누세요(/).

In [6]:
# 여기에 코드를 작성합니다
a = torch.rand(3,3)
b = torch.rand(3,3)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[0.6685, 0.5248, 0.6902],
        [0.8740, 0.3217, 0.4927],
        [1.1278, 0.9737, 0.4993]])
tensor([[ 0.4986,  0.1706,  0.2537],
        [ 0.5097,  0.0364, -0.2321],
        [-0.5929,  0.4738,  0.1123]])
tensor([[0.0496, 0.0616, 0.1030],
        [0.1260, 0.0255, 0.0472],
        [0.2301, 0.1809, 0.0592]])
tensor([[6.8668, 1.9634, 2.1621],
        [3.7984, 1.2551, 0.3596],
        [0.3109, 2.8957, 1.5807]])


### 3. 행렬의 내적 연산
1. 2×3 크기의 Tensor A를 다음 값으로 생성하세요:
  - `[[1,2,3], [4,5,6]]`
2. 3×2 크기의 Tensor B를 다음 값으로 생성하세요:
  - `[[7,8],[9,10],[11,12]]`
3. 두 Tensor의 행렬 내적(행렬 곱) A×B를 계산하여 출력하세요.

In [12]:
# 여기에 코드를 작성합니다
ta = torch.tensor([[1,2,3], [4,5,6]])
tb = torch.tensor([[7,8],[9,10],[11,12]])
R = torch.matmul(ta, tb)
print(R)

tensor([[ 58,  64],
        [139, 154]])


### 4. 행렬 연산과 값 제한
1. 이전 문제에서 계산된 행렬 R(결과 행렬 A×B)를 사용하세요
2. 행렬 R의 각 요소에 10을 더하세요.
3. R의 각 요소를 100보다 큰 값은 100으로, 나머지는 그대로 유지하도록 제한하세요.

In [13]:
# 여기에 코드를 작성합니다
added = R+10
print(added)
answer = torch.clamp(added, max=100)
print(answer)

tensor([[ 68,  74],
        [149, 164]])
tensor([[ 68,  74],
        [100, 100]])


### 5. 행렬의 열별 합계 계산
1. 5×5 크기의 Tensor M을 다음 값으로 생성하세요
    ```
    [[1, 2, 3, 4, 5],
     [6, 7, 8, 9, 10],
     [11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20],
     [21, 22, 23, 24, 25]]
    ```

2. 행렬 M의 각 열의 합계를 계산하세요.

In [14]:
# 여기에 코드를 작성합니다
M = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
answer = torch.sum(M, dim=0)
print(answer)

tensor([55, 60, 65, 70, 75])
